<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions
		targetNamespace="http://it.univaq.connectpa.publicbillposting.sia/caCDPosterService"
		name="cdMobileAppSetInvocationAddressService"
		xmlns="http://schemas.xmlsoap.org/wsdl/"
		xmlns:wsp="http://www.w3.org/ns/ws-policy"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
		xmlns:tns="http://it.univaq.connectpa.publicbillposting.sia/caCDPosterService"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">

	<types>
		<xsd:schema targetNamespace="http://it.univaq.connectpa.publicbillposting.sia/caCDPosterService">

			<xsd:element name="setInvocationAddress" type="tns:setInvocationAddress" />
			<xsd:element name="setInvocationAddressResponse" type="tns:setInvocationAddressResponse" />

			<xsd:complexType name="setInvocationAddress">
				<xsd:sequence>
					<xsd:element name="participantName" type="xsd:string" minOccurs="0" />
					<xsd:element name="address" type="xsd:string" minOccurs="0" />
				</xsd:sequence>
			</xsd:complexType>

			<xsd:complexType name="setInvocationAddressResponse">
				<xsd:sequence />
			</xsd:complexType>
		</xsd:schema>
	</types>

	<message name="setInvocationAddress">
		<part name="request" element="tns:setInvocationAddress" />
	</message>

	<message name="setInvocationAddressResponse">
		<part name="response" element="tns:setInvocationAddressResponse" />
	</message>

	<portType name="SetInvocationAddressPT">
		<operation name="setInvocationAddress">
			<input wsam:Action="http://it.univaq.connectpa.publicbillposting.sia/SetInvocationAddressPT/setInvocationAddressRequest" message="tns:setInvocationAddress" />
			<output wsam:Action="http://it.univaq.connectpa.publicbillposting.sia/SetInvocationAddressPT/setInvocationAddressResponse" message="tns:setInvocationAddressResponse" />
		</operation>
	</portType>

	<binding name="SetInvocationAddressPortBinding" type="tns:SetInvocationAddressPT">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<operation name="setInvocationAddress">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="caCDPosterServiceSetInvocationAddressService">
		<port name="SetInvocationAddressServicePort" binding="tns:SetInvocationAddressPortBinding">
			<soap:address location="http://localhost:8080/ode/processes/caCDPosterServiceSetInvocationAddress" />
		</port>
	</service>
</definitions>

