<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	name="propertiesAliases"
	targetNamespace="http://it.univaq.connectpa.publicbillposting/propertiesAliases"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:cacdpaymentservice="http://it.univaq.connectpa.publicbillposting/caCDPaymentService">
	

  <import location="caCDPaymentService.wsdl" namespace="http://it.univaq.connectpa.publicbillposting/caCDPaymentService"/>

  <vprop:propertyAlias messageType="cacdpaymentservice:paymentData" part="request" propertyName="properties:instanceID">
    <vprop:query>requestID</vprop:query>
  </vprop:propertyAlias>

  <vprop:propertyAlias messageType="cacdpaymentservice:receipt" part="response" propertyName="properties:instanceID">
    <vprop:query>requestID</vprop:query>
  </vprop:propertyAlias>

</definitions>
